module.exports = {
	select: require('./lib/select'),
	create: require('./lib/create'),
	on: require('./lib/on'),
	attr: require('./lib/attr'),
	data: require('./lib/data'),
	style: require('./lib/style'),
	text: require('./lib/text'),
	value: require('./lib/value'),
	html: require('./lib/html'),
	children: require('./lib/children'),
	getChild: require('./lib/get-child'),
	hasClass: require('./lib/has-class'),
	addClass: require('./lib/add-class'),
	removeClass: require('./lib/remove-class'),
	toggleClass: require('./lib/toggle-class'),
	replaceClass: require('./lib/replace-class'),
};
